Repository github-for-unity/Unity, pull requests merged in 2018-05, with the labels that each got.

#573 Better user metrics
  src/GitHub.Api/Application/ApplicationManagerBase.cs
  src/GitHub.Api/Helpers/Constants.cs
  src/GitHub.Api/Metrics/IUsageTracker.cs
  src/GitHub.Api/Metrics/UsageModel.cs
  src/GitHub.Api/Metrics/UsageTracker.cs
  src/GitHub.Api/Tasks/ITaskManager.cs
  src/GitHub.Api/Tasks/TaskManager.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/EntryPoint.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/AuthenticationView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/BranchesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/HistoryView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Subview.cs
Labels: ready-for-review

#713 Per session usage metrics of GitHub for Unity
  src/GitHub.Api/Application/ApplicationManagerBase.cs
  src/GitHub.Api/Metrics/UsageModel.cs
  src/GitHub.Api/Metrics/UsageTracker.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationCache.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationManager.cs
Labels: ready-for-review

#714 Removing NumberOf prefix from metrics
  src/GitHub.Api/Metrics/UsageModel.cs
  src/GitHub.Api/Metrics/UsageTracker.cs
Labels: ready-for-review

#715 Force unlock by default when unlocking from the Settings view
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/SettingsView.cs
Labels: ready-for-review

#724 Adding comments to AssemblyResources.ToFile(...)
  src/GitHub.Api/Helpers/AssemblyResources.cs
Labels: ready-for-review

#726 Adding a null/empty check for last skipped version
  src/GitHub.Api/Primitives/TheVersion.cs
  src/UnityExtension/Assets/Editor/UnityTests/VersionTests.cs
Labels: ready-for-review

#728 The log on mac should be in ~/Library/Logs.
  .github/ISSUE_TEMPLATE.md
  README.md
  src/GitHub.Api/Platform/DefaultEnvironment.cs
Labels: ready-for-review

#729 Removing merge conflict file
  src/GitHub.Api/Metrics/UsageTracker.cs.orig
Labels: ready-for-review

#730 Hookup Handlers error
  src/GitHub.Api/Git/RepositoryManager.cs
Labels: work-in-progress

#733 Don't throw errors if we can't download the latest json feed
  src/UnityExtension/Assets/Editor/GitHub.Unity/UpdateCheck.cs
Labels: ready-for-review

#734 Remove debug logging, this is just spamming my debug log
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
Labels: ready-for-review

#735 Fix wrong output path
  src/GitHub.Api/Primitives/Package.cs
Labels: bug, ready-for-review

#736 Update git lfs mac to 2.4.0
  generate-package.sh
  src/GitHub.Api/PlatformResources/mac/git-lfs.json
  src/GitHub.Api/PlatformResources/mac/git-lfs.zip
Labels: ready-for-review

#738 Validate git installations by version and fix setting up custom gits
  generate-package.sh
  src/GitHub.Api/Application/ApplicationManagerBase.cs
  src/GitHub.Api/Application/IApplicationManager.cs
  src/GitHub.Api/Git/GitClient.cs
  src/GitHub.Api/Git/IRepository.cs
  src/GitHub.Api/Git/Repository.cs
  src/GitHub.Api/Git/RepositoryManager.cs
  src/GitHub.Api/Git/Tasks/GitLfsVersionTask.cs
  src/GitHub.Api/Git/Tasks/GitUnlockTask.cs
  src/GitHub.Api/Git/Tasks/GitVersionTask.cs
  src/GitHub.Api/Git/ValidateGitInstallResult.cs
  src/GitHub.Api/GitHub.Api.csproj
  src/GitHub.Api/Helpers/AssemblyResources.cs
  src/GitHub.Api/Helpers/Constants.cs
  src/GitHub.Api/Helpers/Progress.cs
  src/GitHub.Api/Installer/GitInstaller.cs
  src/GitHub.Api/Installer/OctorunInstaller.cs
  src/GitHub.Api/Installer/UnzipTask.cs
  src/GitHub.Api/Installer/ZipHelper.cs
  src/GitHub.Api/Localization.Designer.cs
  src/GitHub.Api/Localization.resx
  src/GitHub.Api/OutputProcessors/LfsVersionOutputProcessor.cs
  src/GitHub.Api/OutputProcessors/ProcessManager.cs
  src/GitHub.Api/OutputProcessors/VersionOutputProcessor.cs
  src/GitHub.Api/Platform/DefaultEnvironment.cs
  src/GitHub.Api/Platform/IEnvironment.cs
  src/GitHub.Api/Platform/ProcessEnvironment.cs
  src/GitHub.Api/Platform/Settings.cs
  src/GitHub.Api/Primitives/Package.cs
  src/GitHub.Api/Primitives/TheVersion.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationManager.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/EntryPoint.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/GitPathView.cs
  src/tests/CommandLine/Program.cs
  src/tests/IntegrationTests/BaseIntegrationTest.cs
  src/tests/IntegrationTests/Git/GitClientTests.cs
  src/tests/IntegrationTests/Installer/GitInstallerTests.cs
  src/tests/IntegrationTests/IntegrationTestEnvironment.cs
  src/tests/IntegrationTests/IntegrationTests.csproj
  src/tests/IntegrationTests/PlatformResources/linux/.placeholder
  src/tests/IntegrationTests/PlatformResources/linux/git-lfs.zip
  src/tests/IntegrationTests/PlatformResources/linux/git-lfs.zip.md5
  src/tests/IntegrationTests/PlatformResources/linux/gitconfig
  src/tests/IntegrationTests/PlatformResources/mac/git-lfs.zip
  src/tests/IntegrationTests/PlatformResources/mac/git-lfs.zip.md5
  src/tests/IntegrationTests/PlatformResources/mac/gitconfig
  src/tests/IntegrationTests/PlatformResources/windows/.gitattributes
  src/tests/IntegrationTests/PlatformResources/windows/git-lfs.zip
  src/tests/IntegrationTests/PlatformResources/windows/git-lfs.zip.md5
  src/tests/IntegrationTests/PlatformResources/windows/git.zip.md5
  src/tests/IntegrationTests/PlatformResources/windows/gitconfig
  src/tests/TaskSystemIntegrationTests/Tests.cs
  src/tests/TestWebServer/files/unity/git/windows/git-full.zip
  src/tests/TestWebServer/files/unity/git/windows/git.json
  src/tests/TestWebServer/files/unity/git/windows/git.zip
  src/tests/UnitTests/IO/LfsVersionOutputProcessorTests.cs
  src/tests/UnitTests/IO/VersionOutputProcessorTests.cs
Labels: ready-for-review

#741 Clean up the package
  lib/Mono.Security.dll
  src/GitHub.Api/GitHub.Api.csproj
  src/UnityExtension/Assets/Editor/GitHub.Unity/GitHub.Unity.csproj
  src/UnityExtension/Assets/Editor/GitHub.Unity/Tools/MozRoots.cs
  src/packaging/CopyLibrariesToDevelopmentFolder/CopyLibrariesToDevelopmentFolder.csproj
  unity/PackageProject/Assets/Plugins/GitHub/Editor/Mono.Security.dll.meta
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources.meta
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources/linux.meta
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources/linux/gitconfig
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources/linux/gitconfig.meta
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources/mac.meta
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources/mac/gitconfig
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources/mac/gitconfig.meta
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources/windows.meta
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources/windows/gitconfig
  unity/PackageProject/Assets/Plugins/GitHub/Editor/PlatformResources/windows/gitconfig.meta
  unity/PackageProject/Assets/Plugins/GitHub/Editor/Resources.meta
Labels: ready-for-review

#742 Cleaning up a few debug things that slipped through
  src/UnityExtension/Assets/Editor/GitHub.Unity/EntryPoint.cs
Labels: ready-for-review

#744 Setting UnityYamlMerge options on repo initialization
  src/GitHub.Api/Application/ApplicationManagerBase.cs
Labels: ready-for-review

#743 We can only run local git commands if there's a git repo
  src/GitHub.Api/Application/ApplicationManagerBase.cs
Labels: ready-for-review

#745 Validating cached data on initialize in Project explorer
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs
Labels: ready-for-review

#747 Ensure log path exists
  src/GitHub.Api/Platform/DefaultEnvironment.cs
Labels: ready-for-review

#748 Add .vscode/ dir to the .gitignore
  .gitignore
Labels: ready-for-review

#746 Fix recursive filesystem enumeration
  src/GitHub.Api/IO/FileSystem.cs
  src/GitHub.Api/Installer/GitInstaller.cs
  src/GitHub.Api/Platform/ProcessEnvironment.cs
Labels: ready-for-review

#750 Updating ApplicationConfiguration webTimeout from settings
  src/GitHub.Api/Application/ApplicationManagerBase.cs
Labels: ready-for-review

#753 Window.currentBranchAndRemoteHasUpdate never reset to false
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
Labels: ready-for-review

#755 Use http everywhere
  src/GitHub.Api/Installer/GitInstaller.cs
  src/GitHub.Api/Installer/OctorunInstaller.cs
  src/GitHub.Api/Primitives/Package.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UpdateCheck.cs
Labels: ready-for-review

#754 Fix version comparisons bugs
  common/SolutionInfo.cs
  src/GitHub.Api/Application/ApplicationConfiguration.cs
  src/GitHub.Api/Metrics/UsageTracker.cs
  src/GitHub.Api/Primitives/TheVersion.cs
  src/UnityExtension/Assets/Editor/UnityTests/VersionTests.cs
  src/tests/IntegrationTests/Metrics/MetricsTests.cs
Labels: ready-for-review

#756 Remove ambiguous variables/parameters
  src/GitHub.Api/Application/ApplicationManagerBase.cs
  src/GitHub.Api/Managers/Downloader.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/GitPathView.cs
Labels: ready-for-review

#759 Removing some unused fields in Window
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
Labels: ready-for-review

#758 Enable/disable the git path buttons in the settings view appropriately
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/GitPathView.cs
Labels: ready-for-review

#760 Moving the toolbar
  src/GitHub.Api/Localization.Designer.cs
  src/GitHub.Api/Localization.resx
  src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Styles.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/HistoryView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
Labels: ready-for-review

#761 Capturing when the GitPathView has changes in a property
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/GitPathView.cs
Labels: ready-for-review

#757 Fix "Use bundled git" behaviour
  src/GitHub.Api/Installer/GitInstaller.cs
  src/GitHub.Api/OutputProcessors/VersionOutputProcessor.cs
  src/GitHub.Api/Platform/DefaultEnvironment.cs
  src/GitHub.Api/PlatformResources/mac/git-lfs.json
  src/GitHub.Api/PlatformResources/windows/git.json
  src/GitHub.Api/PlatformResources/windows/git.zip
  src/GitHub.Api/Primitives/Package.cs
  src/GitHub.Api/Primitives/TheVersion.cs
  src/GitHub.Api/Tasks/ProcessTask.cs
  src/GitHub.Api/Tasks/TaskBase.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/EntryPoint.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/GitPathView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UpdateCheck.cs
  src/UnityExtension/Assets/Editor/UnityTests/VersionTests.cs
  src/tests/IntegrationTests/BaseIntegrationTest.cs
  src/tests/IntegrationTests/Git/GitClientTests.cs
  src/tests/IntegrationTests/Installer/GitInstallerTests.cs
  src/tests/TestWebServer/TestWebServer.csproj
  src/tests/TestWebServer/files/unity/git/mac/git-lfs.json
  src/tests/TestWebServer/files/unity/git/windows/git-full.zip
  src/tests/TestWebServer/files/unity/git/windows/git-lfs.json
  src/tests/TestWebServer/files/unity/git/windows/git-lfs.zip
  src/tests/TestWebServer/files/unity/git/windows/git-slim.zip
  src/tests/TestWebServer/files/unity/git/windows/git.json
  src/tests/TestWebServer/files/unity/git/windows/gitconfig
Labels: ready-for-review

#765 Add a refresh button to the action bar
  src/GitHub.Api/Git/IRepository.cs
  src/GitHub.Api/Git/Repository.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Styles.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/BranchesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/HistoryView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/SettingsView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
Labels: ready-for-review

#764 Only clearing the commit message and body on commit success
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
Labels: ready-for-review

#770 Using git errors in popup messages
  src/GitHub.Api/Localization.Designer.cs
  src/GitHub.Api/Localization.resx
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/SettingsView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
Labels: ready-for-review

#768 Remove reference to Octokit solution
  docs/contributing/how-to-build.md
Labels: documentation, ready-for-review

#725 Dedicated view to Locked files
  src/GitHub.Api/Extensions/StringExtensions.cs
  src/GitHub.Api/Git/GitClient.cs
  src/GitHub.Api/Git/GitLock.cs
  src/GitHub.Api/Git/GitLogEntry.cs
  src/GitHub.Api/Git/IRepository.cs
  src/GitHub.Api/Git/Repository.cs
  src/GitHub.Api/Helpers/Constants.cs
  src/GitHub.Api/Helpers/SimpleJson.cs
  src/GitHub.Api/Localization.Designer.cs
  src/GitHub.Api/Localization.resx
  src/GitHub.Api/Primitives/TheVersion.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/GitHub.Unity.csproj
  src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Styles.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/BaseWindow.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/IView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/InitProjectView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/LocksView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/SettingsView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Subview.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/UserSettingsView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UpdateCheck.cs
  src/tests/UnitTests/Primitives/SerializationTests.cs
Labels: work-in-progress

#772 Readme.md fixes
  README.md
Labels: ready-for-review

#773 Including the readme.pdf in the package project
  unity/PackageProject/Assets/Plugins/GitHub/Editor/README.pdf
Labels: ready-for-review

#776 Fixes to credits.txt
  CREDITS.txt
Labels: ready-for-review

#777 Shortening a few more exception messages
  src/GitHub.Api/Metrics/UsageTracker.cs
  src/GitHub.Api/Primitives/Package.cs
Labels: ready-for-review

#779 GitLocks NullReferenceException
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
Labels: ready-for-review

#790 isBusy should not be serialized
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/LocksView.cs
Labels: ready-for-review

#791 Remove debug logging
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
Labels: ready-for-review

#789 Ensure environment is never initialized off the main thread
  src/GitHub.Api/Application/ApplicationManagerBase.cs
  src/GitHub.Api/Application/IApplicationManager.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationManager.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/EntryPoint.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/ScriptObjectSingleton.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/GitPathView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/LocksView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UpdateCheck.cs
Labels: ready-for-review

#798 Missing true in force unlock operation
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs
Labels: ready-for-review

#801 Add header to the request if we have the token
  octorun/src/bin/app-usage.js
  octorun/version
  src/GitHub.Api/Installer/OctorunInstaller.cs
  src/GitHub.Api/Resources/octorun.zip
  src/GitHub.Api/Resources/octorun.zip.md5
Labels: ready-for-review

#805 Discard should always ask for confirmation
  src/GitHub.Api/Localization.Designer.cs
  src/GitHub.Api/Localization.resx
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
Labels: ready-for-review

#806 Usage tracker should never be null
  src/GitHub.Api/Application/ApplicationManagerBase.cs
  src/GitHub.Api/Metrics/IMetricsService.cs
  src/GitHub.Api/Metrics/IUsageTracker.cs
  src/GitHub.Api/Metrics/UsageTracker.cs
  src/tests/IntegrationTests/Metrics/MetricsTests.cs
Labels: ready-for-review

#807 ProjectWindow Initialization cleanups
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs
Labels: ready-for-review

#808 Make sure we shutdown promptly
  src/GitHub.Api/Managers/Downloader.cs
  src/GitHub.Api/Tasks/ActionTask.cs
  src/GitHub.Api/Tasks/ProcessTask.cs
  src/GitHub.Api/Tasks/TaskBase.cs
Labels: ready-for-review
