Repository github-for-unity/Unity, pull requests merged in 2018-06, with the labels that each got.

#794 Adding git repo size and lfs disk usage to metrics
  src/GitHub.Api/Application/ApplicationManagerBase.cs
  src/GitHub.Api/Git/GitClient.cs
  src/GitHub.Api/Git/GitCountObjects.cs
  src/GitHub.Api/Git/Tasks/GitCountObjectsTask.cs
  src/GitHub.Api/GitHub.Api.csproj
  src/GitHub.Api/Metrics/IUsageTracker.cs
  src/GitHub.Api/Metrics/UsageModel.cs
  src/GitHub.Api/Metrics/UsageTracker.cs
  src/GitHub.Api/OutputProcessors/GitCountObjectsProcessor.cs
  src/GitHub.Api/OutputProcessors/LinuxDiskUsageOutputProcessor.cs
  src/GitHub.Api/OutputProcessors/WindowsDiskUsageOutputProcessor.cs
  src/GitHub.Api/Platform/LinuxDiskUsageTask.cs
  src/GitHub.Api/Platform/WindowsDiskUsageTask.cs
  src/GitHub.Api/Tasks/ITaskManager.cs
  src/GitHub.Api/Tasks/TaskManager.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/AuthenticationView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/BranchesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/LocksView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/PublishView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
  src/tests/IntegrationTests/Metrics/MetricsTests.cs
  src/tests/TestUtils/Helpers/AssertExtensions.cs
  src/tests/UnitTests/IO/CountObjectProcessorTests.cs
  src/tests/UnitTests/IO/LinuxDiskUsageOutputProcessorTests.cs
  src/tests/UnitTests/IO/WindowsDiskUsageOutputProcessorTests.cs
  src/tests/UnitTests/UnitTests.csproj
Labels: ready-for-review

#817 Don't trample an existing SynchronizationContext
  src/GitHub.Api/Application/ApiClient.cs
  src/GitHub.Api/Application/ApplicationManagerBase.cs
  src/GitHub.Api/Application/IApiClient.cs
  src/GitHub.Api/Authentication/ICredentialManager.cs
  src/GitHub.Api/Authentication/IKeychain.cs
  src/GitHub.Api/Authentication/ILoginManager.cs
  src/GitHub.Api/Authentication/Keychain.cs
  src/GitHub.Api/Authentication/LoginManager.cs
  src/GitHub.Api/Git/GitCredentialManager.cs
  src/GitHub.Api/Threading/ThreadingHelper.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/Services/AuthenticationService.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/AuthenticationView.cs
  src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs
  src/tests/UnitTests/Authentication/KeychainTests.cs
Labels: bug, ready-for-review

#822 Fix regression when reading output in non-ascii locales
  src/GitHub.Api/Tasks/ProcessTask.cs
Labels: ready-for-review

#826 Make sure we always send the correct user agent
  octorun/src/api.js
  octorun/src/authentication.js
  octorun/src/octokit.js
  src/GitHub.Api/Application/ApplicationInfo.cs
Labels: ready-for-review

#827 Adding a "How to Authenticate" document
  docs/using/authenticating-to-github.md
  docs/using/images/github-authenticate.png
  docs/using/images/github-menu-item.png
  docs/using/images/github-sign-in-button.png
  docs/using/images/github-two-factor.png
Labels: documentation, ready-for-review

#832 Add docs for managing branches
  docs/using/images/branches-initial-view.png
  docs/using/images/create-new-branch-view.png
  docs/using/images/delete-dialog.png
  docs/using/images/name-branch.png
  docs/using/images/new-branch-created.png
  docs/using/images/switch-confirmation.png
  docs/using/images/switch-or-delete.png
  docs/using/images/switched-branches.png
  docs/using/managing-branches.md
Labels: documentation, ready-for-review

#829 Add documentation for working with changes
  docs/using/images/changes-view.png
  docs/using/images/confirm-pull-changes.png
  docs/using/images/confirm-push-changes.png
  docs/using/images/confirm-revert.png
  docs/using/images/post-commit-view.png
  docs/using/images/post-push-history-view.png
  docs/using/images/pull-view.png
  docs/using/images/push-view.png
  docs/using/images/revert-commit.png
  docs/using/images/revert.png
  docs/using/images/success-pull-changes.png
  docs/using/images/success-push-changes.png
  docs/using/working-with-changes.md
Labels: documentation, ready-for-review

#838 Fixing date parsing for VSTS repos
  src/GitHub.Api/Helpers/Constants.cs
  src/GitHub.Api/Helpers/SimpleJson.cs
  src/tests/UnitTests/IO/LockOutputProcessorTests.cs
  src/tests/UnitTests/Primitives/SerializationTests.cs
Labels: ready-for-review
